### ISSUE TITLE
(viewer, GUI) Give users control over terrain texture repeats

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#1475]
## Test plan

See:

- https://github.com/secondlife/viewer/pull/1667
- https://github.com/secondlife/viewer/pull/1724

See also "Saving PBR Terrain Texture Transforms" in https://github.com/secondlife/viewer/blob/develop/doc/testplans/pbr_terrain_composition.md

**Comment by cosmic-linden** [comment]
Caladbolg has given design feedback, however Steeltoe has not. Setting to integrated, with the understanding that there may be another UI design pass.

**Comment by cosmic-linden** [comment]
@Dan-Linden Test plan has been added.

**Comment by dmytrohproductengine** [comment]
Deferred QA.

Verified on the Second Life Release 7.1.9.9865199239 (64bit) build on WIn10/OSX in the scope of [secondlife/iqa#282](https://github.com/secondlife/iqa/issues/282).

Could you please provide a test plan and a region to check?

This behavior should be checked with the "Advanced"→"Show Debug Settings"→"RenderTerrainPBRTransformsEnabled" option set to a TRUE value.

But on Agni PE Regions no terrain changes were observed (perhaps, due to a lack of server support for PE regions) (see "iqa_282.mp4").

**Also**, the "PBR Metallic Roughness" terrain materials are switched to "Terrain Textures" in the "Terrain" tab "Region/Estate" floater after applying the terrain textures/PBR materials to a region (see [secondlife/viewer/issues/2038](https://github.com/secondlife/viewer/issues/2038)).

**Comment by cosmic-linden** [comment]
@dmytrohproductengine A simulator running the latest version of "2024.07 - Picnic in the park" should support this feature. I think Rumpus Room 2048 on Aditi is either on that channel, or the more current simulator develop branch. However, there has recently been some churn in the network protocol which may impede the viewer's ability to set the feature flag if the viewer and simulator versions are not in sync.

I would recommend:

- Check that the simulator contains this change: https://github.com/secondlife/server/pull/1241
- Check that the viewer contains this change: https://github.com/secondlife/viewer/pull/2002
- Due to a known bug, the Region/Estate floater may need to be opened/closed an additional time in order for the UI changes to take effect. This is reflected in the test plan.

Another note: For a supported viewer, no visible changes to the terrain are expected by toggling "RenderTerrainPBRTransformsEnabled". "RenderTerrainPBRTransformsEnabled". The feature flag "RenderTerrainPBRTransformsEnabled" just toggles the UI which can set PBR terrain texture transforms, which is available for PBR terrain only.

**Comment by dmytrohproductengine** [comment]
@cosmic-linden, thanks for the clarification.

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.9.9865199239 (64bit) build on Win10/OSX in the scope of secondlife/iqa#282.
