### ISSUE TITLE
Fix GLTF glb upload

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1596]
1. Connect to Fractal on aditi
2. Click Develop->GLTF->Open and choose a .glb file
3. Click Develop->GLTF->Upload

OBSERVE: Textures do not upload and upload fails

**Comment by akleshchev** [comment]
Textures uploaded just fine for me and appeared in inventory, but 'final' material upload took 1L$ an I don't see it in inventory.

**Comment by RunitaiLinden** [comment]
> Textures uploaded just fine for me and appeared in inventory, but 'final' material upload took 1L$ an I don't see it in inventory.

That final upload isn't a .material, it's a .gltf and .glbin, and it doesn't end up in inventory, it gets applied to the selected prim.  From there you can take it to inventory.  We have the L$ sink set to L$1 for now and will update that when we figure out the pricing model.

**Comment by valeriiaaproductengine** [comment]
Failed QA.

On OSX Textures uploaded good and appeared in inventory.

Unable to check this ticket on Aditi on Win10 at secondlife://Aditi/secondlife/Fractal/128/136/2 location. Due to the [first](https://github.com/secondlife/viewer/issues/1894) issue, the viewer menu will become inoperative.

Verified on the Second Life Release 7.1.9.9620320242 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/266.

**Comment by AtlasLinden** [comment]
1894 is integrated in DeltaFPS. Moving milestone and sending back to testing

**Comment by dmytrohproductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.10.10582490681 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.
