### ISSUE TITLE
Don't store texture in system memory unless absolutely necessary

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1836]
### Description

The viewer currently stores textures in system memory under more circumstances than it should.  Remove "Cached Raw Image" members and functions to reduce overall memory usage.

Refactor code that relied on mCachedRawImage:
- sculpts
- thumbnails
- texture uploads
- down rezzing textures

**Comment by RunitaiLinden** [comment]
Pushed to develop.

Texture downrezzing now happens much more quickly and with no visual or performance side effects.  Also, there are no longer frame stalls from creating brightness/darkness bumpmaps.  Viewer system memory footprint should be lower.

For QA --

This change touched a lot of code.  Take care to check for regressions in texture uploads, downloads, sculpts, bumpmaps, thumbnails, BoM layers, etc.

It is expected that brightness/darkness bumpmaps will look somewhat different, but they should be mostly the same as before.

**Comment by katerynamproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.10.10622905308 (64bit) on Win10/OSX in the scope of secondlife/iqa#316.

Texture uploads, downloads, sculpts, bumpmaps, thumbnails, BoM layers are looking normal. See the screenshot: 
<img width="1439" alt="Screenshot 2024-08-30 at 3 48 18 PM" src="https://github.com/user-attachments/assets/d97651a2-2c34-4f29-8efd-9a0f7f3382ff">

According to the comment https://github.com/secondlife/viewer/issues/2024#issuecomment-2321417363 , if move some distance away from some sculptures, it looks corrupted. That is expected behavior.
