### ISSUE TITLE
Fix redundant feature flag for PBR terrain repeats (viewer)

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#1885]
## Test plan

See "Feature: PBR Terrain Texture Transforms" in https://github.com/secondlife/viewer/blob/develop/doc/testplans/pbr_terrain_composition.md

**Comment by sergiiiproductengine** [comment]
The PBR terrain texture transform flag (`RenderTerrainPBRTransformsEnabled`) is not automatically enabled when logging in or teleporting to region where the PBR terrain texture feature is enabled.

Also, I don't see any changes in UI of the Terrain tab, when the `RenderTerrainPBRTransformsEnabled` is enabled.

Also, we have https://github.com/secondlife/viewer/issues/2003 and https://github.com/secondlife/viewer/issues/2005 tickets,  where one of them for viewer and another one for server. As I understood these tickets should undo this ticket.

So, could you please clarify, what is the expected behaviour for these tickets and where we can test this (viewer/simulator/regions)?

**Comment by cosmic-linden** [comment]
@sergiiiproductengine This ticket is superceded by #2003 and #2005 .

Testing for PBR terrain repeats should be done on a viewer containing atlasaurus (which should be in the release viewer now), while connecting to a simulator containing picnic.

There was previously a bug where the feature flag would not take effect until the floater was closed and reopened. It is possible that bug may be occurring.

If the feature still isn't enabled, that may be an issue with the server which needs to be looked into.

**Comment by sergiiiproductengine** [comment]
Thank you, @cosmic-linden !

> This ticket is superceded by #2003 and #2005 .

Could you please clarify does this mean that the test plan is not relevant and perhaps this ticket should be closed?

Also, some questions were added to the #2003 as it is not entirely clear what exactly was undo (the current behaviour is described there).

It is also not entirely clear what should be tested in the #2005, so the test plan request was added in that ticket.

Could you please review #2003 and #2005 tickets and update them accordingly?

**Comment by cosmic-linden** [comment]
@sergiiiproductengine Taking a look now

**Comment by brad-linden** [comment]
confirmed with cosmic that this test plan is no longer relevant and should be closed
