### ISSUE TITLE
Undo: Fix redundant feature flag for PBR terrain repeats (viewer)

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#2003]
Undo https://github.com/secondlife/viewer/issues/1885, preserve test plan

## Test plan

See "Feature: PBR Terrain Texture Transforms" in https://github.com/secondlife/viewer/blob/develop/doc/testplans/pbr_terrain_composition.md

**Comment by sergiiiproductengine** [comment]
Deferred QA.

Could you please clarify what was exactly undo in the '[Feature: PBR Terrain Texture Transforms](https://github.com/secondlife/viewer/blob/develop/doc/testplans/pbr_terrain_composition.md)' and what is expected behaviour for this?

According to the test plan: 
The PBR terrain texture transform flag should be set automatically when logging in/teleporting to a new region.

Actual (not expected according to the test plan):
The PBR terrain texture transform flag turns off after logging in or teleporting to a region where the `RenderTerrainPBRTransformsEnabled` was enabled before teleport/relog.

As expected according to the test plan:
When the PBR terrain texture transform feature is enabled (`RenderTerrainPBRTransformsEnabled` is True):
- Transforms tab appears in Region/Estate > Terrain and the user can change the texture transforms for the terrain in the current region (scale, offset, and rotation) after check "PBR Metallic Roughness"
- the controls for texture transforms is hidden after uncheck "PBR Metallic Roughness"

Note: known issue mentioned in the test plan still reproduces ('The Region/Estate floater may have to be closed/reopened a second time in order for the UI overhaul to take effect, after teleporting between regions that do and do not have the feature flag set').
I didn't find corresponding ticket, so could you please clarify, maybe the new issue should be filled?

Verified on the Second Life Release 7.1.10.10622905308 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.

**Comment by cosmic-linden** [comment]
@sergiiiproductengine It sounds like this is a failure on the viewer side to apply the feature flag. The known issue is the failure mode.

Having to re-open the floater is an acceptable defect when teleporting between regions, as there will come a point where the feature flag will be enabled universally.

However, having to re-open the floater when logged in to the region for the first time is not acceptable. I would consider it a failure of the test plan for this ticket.

**Comment by sergiiiproductengine** [comment]
> However, having to re-open the floater when logged in to the region for the first time is not acceptable. I would consider it a failure of the test plan for this ticket.

Failed QA.

Verified in the scope of https://github.com/secondlife/iqa/issues/316.
Viewer: Second Life Release 7.1.10.10622905308.
Server: Picnic 2024-08-29.10619830788.

Steps to reproduce:
1. Login to [the viewer](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b0fefd6-DeltaFPS1) on Aditi on the Picnic 2024-08-29.10619830788 server (eg Hera2).
2. Turn on Advanced menu (Preferences > Advanced and check 'Show Advanced Menu').
3. Go to Advanced > Show Debug Settings.
4. Change `RenderTerrainPBRTransformsEnabled` setting to TRUE.
5. Go to World > Region/Estate > Terrain and check the Terrain Material 'PBR Metallic Roughness' setting.
6. Click 'Apply' button and reopen Region/Estate floater.
7. Observe 'Transforms' setting appears in Terrain tab under materials swatches.
8. Relog to the viewer.
9. Go to World > Region/Estate > Terrain and check the Terrain Material 'PBR Metallic Roughness' setting (if it is not checked).
10. Observe 'Transforms' setting appears in Terrain tab.
11. Go to Advanced > Show Debug Settings and observe `RenderTerrainPBRTransformsEnabled` setting is FALSE.

Actual result: 
`RenderTerrainPBRTransformsEnabled` setting is FALSE and 'Transforms' setting appears after relog to the viewer.

<details><summary>Actual. screenshot</summary>
<p>

<img width="1680" alt="Screenshot 2024-09-02 at 2 20 21 PM" src="https://github.com/user-attachments/assets/09bda516-dc85-4305-8df8-561b17e56572">

</p>
</details>  

Expected result: `RenderTerrainPBRTransformsEnabled` setting should be TRUE after relog to the viewer.

**Comment by cosmic-linden** [comment]
@sergiiiproductengine

The following is the expected behavior:

1. Log in to a picnic region
2. Open 'Region/Estate' floater > Terrain tab.
3. Check "PBR Metallic Roughness" if it is unchecked.
4. Observe 'Transforms' setting appears in 'Region/Estate' floater.

The following is also expected behavior, but will be of less significance after picnic is deployed widely through the grid:

1. Log in to a NOT picnic region
2. Open 'Region/Estate' floater > Terrain tab.
3. Check "PBR Metallic Roughness" if it is unchecked.
3. Observe 'Transforms' setting DOES NOT appear in 'Region/Estate' floater.

Based on your tests so far, the behavior of `RenderTerrainPBRTransformsEnabled` appears to be inconsistent with my provided test plan. I will look into this.

Feel free to file tickets for any other anomalous behavior.

**Comment by irinabproductengine** [comment]
Hi @cosmic-linden.
Thank you for the clarification.
Now, the 'RenderTerrainPBRTransformsEnabled' flag is not set automatically on the picnic regions.
This flag is set as 'False' and the 'Transforms' setting DOES NOT appear in the 'Region/Estate' floater.
After logging, the flag needs to be set to 'True' through Debug settings.

So we can specify this ticket as Failed QA.

**Comment by cosmic-linden** [comment]
@irinabproductengine Thank you for checking. I have investigated further and determined that there is indeed anomalous behavior with the feature flag on both the server and the viewer. These are being tracked with the following issues:

https://github.com/secondlife/viewer/issues/2490
https://github.com/secondlife/server/issues/1389

I am currently discussing with devs about expediting the viewer-side fix.

**Comment by brad-linden** [comment]
confirmed with cosmic that this ticket is no longer relevant and should be closed.  work will be covered by other issues
