### ISSUE TITLE
Undo: Fix redundant feature flag for PBR terrain repeats (server)

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#2005]
https://github.com/secondlife/server/pull/1241

**Comment by sergiiiproductengine** [comment]
Deferred QA in the scope of https://github.com/secondlife/iqa/issues/316.

Could you please provide a test plan for this ticket?

**Comment by cosmic-linden** [comment]
Developer note: This is simply reverting protocol changes, related to how to apply feature flag in a manner consistent with current best practices.

**Comment by DmitrySProductengine** [comment]
Hi, @cosmic-linden  - thanks for the clarifications.
During the additional investigation, several behaviors were discovered and filled (ticket 1: https://github.com/secondlife/viewer-private/issues/274 and ticket 2: https://github.com/secondlife/viewer-private/issues/275).
It is difficult for us to determine fully how much these behaviors are related to the simulator (in our opinion, ticket 2 is related to the behavior that after the revert, the viewer receives information about the flag from the server).
The PE QA team can also check server tickets but with limited capabilities (no access to server logs, no ability to change anything in the simulator, etc.).
Since we have not been asked to reassign the ticket to the server QA team before, please tell us to whom we can assign it.

**Comment by cosmic-linden** [comment]
Upon further investigation, it seems that I already put this ticket on server QA's radar. However, your newly linked issues are still relevant and I will look into them.

The viewer-side equivalent of this ticket is https://github.com/secondlife/viewer/issues/2003 .

**Comment by brad-linden** [comment]
confirmed with cosmic that this ticket is no longer relevant and should be closed.  work will be covered by other issues
