### ISSUE TITLE
Sculpts getting corrupted by texture downres

### ISSUE THREAD

**Issue by vir-linden** [secondlife/viewer#2024]
### Environment

User report, don't have this info

### Description

Arton Rotaru reports that some Davep recent fixes to develop are causing sculpt maps to drop res, never come back to full rez. Says they drop after 10 minutes or so.

### Reproduction steps

Test in a region with sculpted prims

**Comment by AtlasLinden** [comment]
Reopening for testing

**Comment by valeriiaaproductengine** [comment]
Passed QA.

Now, the textures on the sculptures look correct, tested in the http://maps.secondlife.com/secondlife/Paris%20Couture/20/125/23 location.
But if move some distance away from the sculpture, it looks corrupted. Could you please clarify whether this is expected behavior or is it a bug?
See actual.png and actual2.png:

![actual](https://github.com/user-attachments/assets/1326db76-e540-4f7e-86d4-993ce0f4453a)

![actual2](https://github.com/user-attachments/assets/ede4fb08-26e6-40c4-939f-d4e18ac7b179)


Verified on the Second Life Release 7.1.10.10622905308 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/316.

**Comment by AtlasLinden** [comment]
Sculpt above appearing as such upon zooming out looks to be a bad case of the LODs. 
Treating that as expected behaviour.
