### ISSUE TITLE
Remove SSAO From Reflection Probes

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#2398]
### Description

Reflection probes shouldn't use GPU resources on fine details like that.  Remove the SSAO pass from probe render passes.

**Comment by igorlproductengine** [comment]
Need more info.
Verified on the Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.

Could you please provide more details about this issue? Specifically, could you explain the expected behavior for reflection probes after the SSAO pass is removed? Additionally, it would be helpful to have a test plan to ensure the functionality is thoroughly validated and meets performance expectations.

**Comment by AtlasLinden** [comment]
Unfortunately there's not any ideal way to test this.
Instead perform part 1.1 of the [Material UI Test Plan](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2730917904/Material+Viewer+UI+Test+Plan#1.1-Screen-Space-Ambient-Occlusion) both in and around some reflection probes

**Comment by igorlproductengine** [comment]
Passed QA.

Verified on Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.

According to the part 1.1 of the [Material UI Test Plan](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2730917904/Material+Viewer+UI+Test+Plan#1.1-Screen-Space-Ambient-Occlusion) and some reflection probes.
