### ISSUE TITLE
LLFontGL::render optimizations

### ISSUE THREAD

**Issue by akleshchev** [secondlife/viewer#2411]
LLFontGL::render uses LLRender's Vertex Buffer cache. This results in initialization overtime where long strings allocate a bunch of small buffers, then results in looking for those buffers in cache each frame. Additionally to perfom a search LLFontGL needs to generate a vertex array and then use it to do a hash for seach.

Task:
- Consider making string rendering to need less searches
- Consider using external vertex buffers to avoid searches entirely.

**Comment by AtlasLinden** [comment]
## Test plan
Verify that:
1. Nametags don't visually differ from release and properly follow avatar
2. Various highlights of elements in UI work properly
3. No issues with text of read only notecards

**Comment by DmitrySProductengine** [comment]
Passed QA.
Verified on the Second Life Release 7.1.11.11074622243 (64bit) on Win11/OSX in the scope of [IQA #356](https://github.com/secondlife/iqa/issues/356).
No unexpected behaviors with text, UI and their display were found.

There was a nuance in Windows 11 - during script editing the cursor was white. But the reason turned out to be in the color scheme of the mouse cursor in Windows 11 - it is white by default. After changing to black during script editing the cursor also became black.
