### ISSUE TITLE
Eliminate execution time outliers for updateImageDecodePriority

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#2438]
### Description

updateImageDecodePriority often takes several milliseconds, but typically takes 2us.  Identify source of outliers and eliminate them.

Test plan:
Anything to test?

**Comment by RunitaiLinden** [comment]
Before and after:

![image](https://github.com/user-attachments/assets/dbf24a37-41db-4cc1-87ab-38a7529a8a9d)

Boosts textures that are referenced by more than 1024 faces.  
Skips vsize calculation for boosted textures.
Caches calcPixelArea with a timeout of 10 frames.
Starts removing "mImportanceToCamera" as it is an unneeded complication.

**Comment by TommyTheTerrible** [comment]
So, what happens when a texture has more than 1024 faces? Just leave it at the last mMaxVirtualSize before it reached 1024 faces?

Is this possibly trying to avoid running through all particles? Why not just break from the face loop if a particle is found or check early and continue to avoid the more complex calculations?

**Comment by RunitaiLinden** [comment]
> So, what happens when a texture has more than 1024 faces? Just leave it at the last mMaxVirtualSize before it reached 1024 faces?
> 

It boosts the texture:

`imagep->setBoostLevel(LLViewerFetchedTexture::BOOST_HIGH);`

Which causes it to load at full resolution no matter its vsize.  Has nothing to do with particles.
