### ISSUE TITLE
Fix label typo in PBR terrain texture transforms tab

### ISSUE THREAD

**Issue by cosmic-linden** [secondlife/viewer#2483]
"Offset y" should be "Offset u".

## Test plan

The following labels should be consistent with each other:

- Labels for texture transforms for PBR terrain, in the "Transforms" tab, in the "Terrain" tab, in the region/estate floater
    - Prerequisites: "PBR Metallic Roughness" must be checked in the "Terrain" tab, and PBR terrain transforms feature flag must be enabled. If necessary, manually verify the client functionality by setting the advanced setting `RenderTerrainPBRTransformsEnabled` to TRUE and close/re-open the floater. Further testing aside from a glance at the UI is not required for this particular ticket.
- Labels for GLTF texture transforms in the build menu for prim faces with a PBR material applied

**Comment by dmytrohproductengine** [comment]
Failed QA.
Verified on the Second Life Release 7.1.10.10708851543 (64bit) on Win10/OSX in the scope of [secondlife/iqa#326](https://github.com/secondlife/iqa/issues/326).

This issue is still reproduced in the "Region/estate" floater→"Terrain" tab→"Transforms" tab (see "7.1.10.10708851543_Terrain.png").
This issue is fixed in the "Build" floater→"Textures" tab→PBR Metallic Roughness material applied (see "7.1.10.10708851543_Build.png").

**7.1.10.10708851543_Terrain.png**
![7 1 10 10708851543_Terrain](https://github.com/user-attachments/assets/e9226145-2fa1-4777-875c-7e015fc69753)
**7.1.10.10708851543_Build.png**
![7 1 10 10708851543_Build](https://github.com/user-attachments/assets/3b53e1b5-13f8-466a-95dc-8051fdd9cfd4)

**Comment by cosmic-linden** [comment]
@dmytrohproductengine Sorry, this seems to be some miscommunication on my part - the milestone has been moved back to Develop, as this fix appears to not be in DeltaFPS. Apologies for the inconvenience.

**Comment by igorlproductengine** [comment]
Passed QA.

Verified on Second Life Release 7.1.11.10947335521 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/348.
