### ISSUE TITLE
The "Day Offset" makes a rebound back to 0,5 or 1 value more after moving of 5 units more or less via mouse pointer

### ISSUE THREAD

**Issue by vladyslavasproductengine** [secondlife/viewer#2736]
Reproduction steps

1. Log in the Viewer with the estate manager account.
2. Teleport to a region where the account is an estate manager.
3. Click "World"→"Region/Estate"→"Environment" tab.
4. Set the "Day Lenght (hours)" option to a value (e.g. "5.0").
5. Set the "Day Offset (hours)" option to "0".
6. Move the Day Offset in steps of 5 units more or less (can be done via mouse pointer).

Actual result:
The "Day Offset" makes a rebound back to 0,5 or 1 value more after moving of 5 units more or less via mouse pointer
Depends on choosing units.

Expected result:
The "Day Offset" should change on the choosing value after moving via mouse pointer.

Video:

https://github.com/user-attachments/assets/a3b12723-121c-42e2-bac2-82af83fc4c12

Additional:
This issue is reproduced on Win10/OSX.
This issue was found during testing of https://github.com/secondlife/viewer/issues/2363.
This issue is not reproduced on the current production build Second Life Release 7.1.10.10800445603.

<details><summary>Environment</summary>
<p>

Second Life Release 7.1.11.11074622243 (64bit)
Release Notes

You are at 138.0, 133.0, 22.0 in Product Engine 2 located at simhost-04220be38f2f3414e.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%202/138/133/22
(global coordinates 337,034.0, 307,333.0, 22.0)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (2712.01 MHz)
Memory: 8067 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4894)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: GeForce 940MX/PCIe/SSE2

Windows Graphics Driver Version: 25.21.14.1735
OpenGL Version: 4.6.0 NVIDIA 417.35

Window size: 1920x1001
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 2048MB
Disk cache: Max size 1638.4 MB (8.7% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/29,689 (0.0%)
September 30 2024 04:09:03

</p>
</details>

**Comment by akleshchev** [comment]
This is expected.

Since day length is 5 hours, offset 7 is equal to a day and 2 hours. Viewer shows 2 hours, that's the effective offset.

Server does not accept 0, nor negative values. This mens that setting value like -1 is complicated (trying to encode a negative value was causing Issue #2363), so instead viewer now translate that. Since day is 5 hours long,  -1+5 results in a 4 hour offset. In this case -1 == 4 and behave identically.

I can technically save positive values from 1h to 12h, but in case of setting 0 value will loop to 5 either way (or any negative value will loop to closest possible one). It made no sense for only -12..0 range to loop, so everything loops to smallest positive offset.

**Comment by akleshchev** [comment]
This is technically expected. But aftrer discussion with vir decided to revert changes that caused this. Will reapply changes in develop along with some slider adjustments (ExtraFPS branch isn't a place for exprimenting). Plan is also to discuss with Kyle or steeltoe since behavior should be made more transparent, server changes might be needed as well.

**Comment by LLGuru** [comment]
- Fixed in https://github.com/secondlife/viewer/pull/2912

**Comment by georgebproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11469579464 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/374.
