### ISSUE TITLE
increase maximum Exposure value in preferences to 4.0

### ISSUE THREAD

**Issue by brad-linden** [secondlife/viewer#2916]
### Description

increase max exposure value in preferences to 4.0 
And default exposure ~~should now be 1.5~~ is 1.0

**Comment by brad-linden** [comment]
implemented in PR #2915

**Comment by igorlproductengine** [comment]
Failed QA

Verified on the Second Life Release 7.1.11.11469579464 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/374.

**1. Inconsistency in Maximum Values:**
In the Preferences > Graphics tab, the maximum value for the Brightness (exposure) parameter is set to 4.0. However, when opening the Advanced settings floater, the maximum value for the Exposure parameter is 1.5 instead of 4.0, creating a mismatch between these two settings.
![Image](https://github.com/user-attachments/assets/29c33c57-4a18-42ce-a451-42ac3cdb3b20)


**2. Issue with Resetting Settings:**
Pressing the "Reset to recommended settings" button does not reset the Exposure value to the default of 1.5, which is the expected behavior. This forces users to manually adjust the settings.

**3. Visual Perception and Other Observations:**
The standard environment looks better with an exposure setting of 1.2.
The Exposure setting does not affect the "World > Environment > Midday (Legacy)" option.

**Comment by AtlasLinden** [comment]
1.5 determined to be too bright.
Further discussions to be made on if this should be made 1.2 or a different value.
For now please revert back to 1.0.

**Comment by igorlproductengine** [comment]
**Failed QA.** 
Verified on the Second Life Release 7.1.11.11565212741 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/375.

**Inconsistency in Maximum Values:**
In the Preferences > Graphics tab, the maximum value for the Brightness (exposure) parameter is set to 4.0. However, when opening the Advanced settings floater, the maximum value for the Exposure parameter is 1.5 instead of 4.0, creating a mismatch between these two settings.

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.11982653819 (64bit) on Win10/OSX in the scope of [IQA#395](https://github.com/secondlife/iqa/issues/395).
