### ISSUE TITLE
The World map and Mini-map do not display terrain texture changes, as well as PBR terrain materials

### ISSUE THREAD

**Issue by valeriiaaproductengine** [secondlife/viewer#3073]
### Environment

<details><summary>Environment</summary>
<p>

Second Life Release 7.1.12.11386494836 (64bit)
Release Notes

You are at 187.9, 85.3, 24.1 in Product Engine located at simhost-039ac35d0127be4e0.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/188/85/24
(global coordinates 336,828.0, 307,285.0, 24.1)
Second Life Server 2024-10-15.11356152186
Release Notes

CPU: 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz (2611.2 MHz)
Memory: 16111 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.5073)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5612
OpenGL Version: 4.6.0 NVIDIA 556.12

Window size: 1920x1001
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (0.7% used)

RestrainedLove API: (disabled)
J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Not Connected
Packets Lost: 0/795 (0.0%)
November 12 2024 02:48:14

</p>
</details> 

### Reproduction steps

1. Login to the Second Life Release 7.1.12.11386494836 Viewer on Agni.
2. Select World > Region/Estate > Terrain tab.
3. Change all terrain textures from 4 levels.
4. Click the Mini-Map and World map buttons from the toolbars. 

**Actual result:** The World map and Mini-map do not display terrain texture changes, as well as PBR terrain materials.
**Expected result:** The World map and Mini-map should display terrain texture changes, as well as PBR terrain materials.

**Note:**
This issue is reproduced on the Win10 and OSX.
This issue was found during ad-hoc testing.
This issue is reproduced on the current production build Second Life Release 7.1.10.10800445603.

See actual.png screenshot:

![Image](https://github.com/user-attachments/assets/abc9bb60-ba1b-414b-9c5d-db5f55ca607a)

Actual2.png:

![Image](https://github.com/user-attachments/assets/1fb8c6e4-6f0a-4b7b-bee1-0739bcba5435)

**Comment by Ansariel** [comment]
Aren't the worldmap textures updated every few hours?

**Comment by rohvani** [comment]
Hello there! Thanks for reporting this, @valeriiaaproductengine!

Currently, it is known that mapserver is unable to render PBR textures when generating a map tile. Unfortunately, there is not much we can do to fix that that with our current mapserver implementation, but there are some tentative plans to eventually upgrade mapserver to be a viewer based bot, so that it could render PBR textures as well as other things like mesh.

In regards to the map not updating after changing the textures, we only update the map once per day, so you will not see changes happen instantaneously -- in-order to see the maptile reflect the terrain changes, you must wait at least 24 hours for the next mapserver run.

**Comment by LLGuru** [comment]
Closing this as "Works as expected"
