### ISSUE TITLE
Exposure setting enabled in Vintage mode

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#3171]
### Environment

ExtraFPS 7.1.11.12041172537

### Description

Exposure setting in Advanced is disabled when Vintage mode is turned on but it is not disabled in Graphics tab.
Expected: Both should be disabled when Vintage mode is enabled.

![Image](https://github.com/user-attachments/assets/ce621978-1cc8-44fa-938f-83979d4e936a)

### Reproduction steps

1. Enable Vintage mode in Advanced Graphics
2. Observe Exposure settings

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.12150664210 (64bit) on Win10/OSX in the scope of [IQA#404](https://github.com/secondlife/iqa/issues/404).

For now, there is an option called "HDR and Emissive" instead of "Vintage Mode".

Consulting with @akleshchev, the "HDR and Emissive" option works the other way around:

When the "HDR and Emissive" checkbox is enabled, both "Exposure" sliders are enabled on any graphics preset.
When the "HDR and Emissive" checkbox is disabled, both "Exposure" sliders are disabled and greyed out on any graphics preset.

The "HDR and Emissive" option is disabled by default for "Low" and "Low+" graphics presets.

**iqa#404.png**
![Image](https://github.com/user-attachments/assets/59ec49e0-1209-4924-905e-292444d607be)
