### ISSUE TITLE
Sharpening slider is broken with Vintage mode

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#3172]
### Environment

ExtraFPS 7.1.11.12041172537

### Description

The Sharpening slider has no effect while Vintage mode is enabled

### Reproduction steps

1. Enable Vintage mode
2. Move the Sharpening slider
3. Observe that sharpening does not take effect (Compare with vintage mode disabled)

**Comment by Geenz** [comment]
Vintage mode does not support sharpening.  I'll disable the controls when it's enabled.

**Comment by dmytrohproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.11.12150664210 (64bit) on Win10/OSX in the scope of IQA#404.

Moving the "Sharpening" slider, the sharpening has an effect as expected.

For now, there is an option called "HDR and Emissive" instead of "Vintage Mode".

Consulting with @akleshchev, the "HDR and Emissive" option works the other way around:

When the "HDR and Emissive" checkbox is enabled, the "Sharpening" and "Exposure" sliders are also enabled.
When the "HDR and Emissive" checkbox is disabled, the "Sharpening" and "Exposure" sliders are also disabled and greyed out.

**iqa#404.png**
![Image](https://github.com/user-attachments/assets/5e530259-2a96-4659-a835-fd49563bf79b)
