### ISSUE TITLE
On Low graphics setting, PBR textures in "Midday" shadow are black

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#3224]
### Environment

Second Life Release 7.1.11.12150664210 (64bit)
Release Notes

You are at 149.0, 113.8, 23.4 in TextureTest located at simhost-06c9a56af17a2102e.agni
SLURL: http://maps.secondlife.com/secondlife/TextureTest/149/114/23
(global coordinates 259,989.0, 248,946.0, 23.4)
Second Life Preflight 2024-10-19.11413863173
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.5131)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.6590
OpenGL Version: 4.6.0 NVIDIA 565.90

Window size: 1723x1338
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 64m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 0
Texture memory: 8192MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/5,611 (0.0%)
December 06 2024 10:21:48

### Description

On Low graphics setting, PBR textures in "Midday" shadow are black

### Reproduction steps

1. Create a new Material (default settings are fine) in Inventory and apply it to a box.
2. Set the Environment to "Midday"
3. Look at the side of the box in shadow.
4. Change the Graphics quality to Low

Observed: The side of the box in shadow is black.
Low: ![Image](https://github.com/user-attachments/assets/20b7af5e-7f27-4006-9ec8-552bd2b38c3e)

Expected: It should look similar to Low+ and be darker but not black.
Low+: ![Image](https://github.com/user-attachments/assets/b81b943f-e11b-48e8-9a5a-8e092a257529)

**Comment by Geenz** [comment]
There's a couple of problems with this one - mainly that this is somewhat correct behavior for PBR content.

The reason behind this is the math.  After reviewing the objects, those specific objects have a metallicness of 1.  The higher the metallicness, the darker the diffuse (albedo) gets.  A roughness of 1 further disguises this issue with direct illumination - if you set the roughness to 0 you'll see the other sides of the cubes also go dark.

The reason this phenomena happens is a direct artifact of how PBR is supposed to work.  When you have lower roughness values on highly metallic objects, your specular basically "fills in" the shading in a sense.  We don't really have a great option for this with the old chrome reflection.

A result of this is this is, more or less, expected behavior even though it looks broken.

If enough people take issue with this, and the frame impact isn't the worst, we can look at giving chrome reflections the same radiance/irradiance treatment that we give reflection probes.

**Comment by Dan-Linden** [comment]
Closed as expected behavior.
