### ISSUE TITLE
Fix mirror update stuttering when moving the camera around

### ISSUE THREAD

**Issue by Geenz** [secondlife/viewer#689]

**Comment by Dan-Linden** [comment]
Please add a test plan for expected behavior.

**Comment by Dan-Linden** [comment]
Geenz says this can be closed.

**Comment by igorlproductengine** [comment]
Hello @Dan-Linden. I saw a strange behavior about the reflection of the mirror probe when the camera is focused on the mirror probe:
Steps to reproduce:
1. Login to the viewer.
2. Open inventory and wear some objects. (e.g. Popgun)
3. Create a new mirror or use any existing mirrors.
4. Move the camera to focus on the mirror.
5. Open the "Camera controls" floater.
6. Click on the "Save as preset" button.
7. Move the avatar by the buttons "WASD".

Actual result: The avatar object attachments is frozen on the mirror reflection in the mirror probe after moving the avatar in front of the mirror.
Expected result: The avatar object attachments should not be frozen in the wind in the reflection of the mirror probe.

Note:
This issue is reproduced on Win10/OSX.
This issue is reproduced on the avatar with avatar animation while the avatar is moving in front of the mirror and the avatar isn't displayed in the avatar camera.

Actual video behavior: https://github.com/secondlife/viewer/assets/150452270/3d09e342-bb6f-45f2-bb22-271eb744fa1d

Could you clarify whether this behavior is related to this ticket, or should the new issue be filled?

**Comment by Dan-Linden** [comment]
Looks similar to https://github.com/secondlife/viewer/issues/1493

**Comment by Dan-Linden** [comment]
Filed https://github.com/secondlife/viewer/issues/1659 for the issue reported above by igorlproductengine.
