### ISSUE TITLE
Crash on teleport to Rumpus Room 2048

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#886]
BugSplat [Key Crash 90788](https://app.bugsplat.com/v2/keycrash?stackKeyId=90788&database=SecondLife_Viewer_2018)
Be sure it fixes [this almost identical stack](https://app.bugsplat.com/v2/keycrash?database=SecondLife_Viewer_2018&stackKeyId=90160)

### Environment

Second Life Project Featurettes 7.1.3.7846003013 (64bit)
Release Notes

You are at 128.0, 128.0, 23.1 in Rumpus Room 4 located at simhost-0db2d1a66103f45c7.aditi
SLURL: secondlife://Aditi/secondlife/Rumpus%20Room%204/128/128/23
(global coordinates 35,968.0, 12,672.0, 23.1)
DRTSIM-580 2023-11-22.6961614080
Release Notes

CPU: AMD Ryzen 9 5980HX with Radeon Graphics         (3293.82 MHz)
Memory: 15775 MB
OS Version: Microsoft Windows 10/11 64-bit (Build 22000.2538)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon RX 6800M

Windows Graphics Driver Version: 30.0.15020.1001
OpenGL Version: 4.6.14800 Core Profile Context 21.50.20.01 30.0.15020.1001

Window size: 1680x979
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 11474MB
Disk cache: Max size 1638.4 MB (5.2% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 0/8,640 (0.0%)
February 23 2024 15:31:44

### Description

Crash to desktop.

### Reproduction steps

Repro: 
1. Delete entire cache folder. 
2. Log into Rumpus Room 4 on Aditi. secondlife://Aditi/secondlife/Rumpus%20Room%204/128/128/23
3. Teleport to Rumpus Room 2048. secondlife://Aditi/secondlife/Rumpus%20Room%202048/128/128/2

Observed: Crash to desktop. https://app.bugsplat.com/v2/crash?database=SecondLife_Viewer_2018&id=1430465

Workaround: Without clearing the cache, log into Rumpus Room 4 again and teleport to Rumpus Room 2048. This time it succeeded.

**Comment by brad-linden** [comment]
ok, definitely suspect a larger corruption or violation of invariants happening in this case.  if I work around the immediate crash I can get a later assert to trip in `gPipeline.mRT->deferredScreen.bindTarget()` that the mFBO is null

**Comment by valeriiaaproductengine** [comment]
Reproduction steps

1. Log into Rumpus Room 2048. secondlife://Aditi/secondlife/Rumpus%20Room%202048/160/108/23.
2. Teleport to secondlife://Aditi/secondlife/Product%20Engine%20Hera2/13/99/23.
3. Teleport to secondlife://Aditi/secondlife/Rumpus%20Room%202048/160/108/23 again.

The viewer crashes almost every time.

**Comment by RunitaiLinden** [comment]
Fix pushed but waiting on review.

The corruption was coming from a coroutine.  A coroutine was clearing a map at the same time the "real" main thread was iterating over the map.  Fix was to take work on the coroutine that reaches into application state and send it back to the "real" main thread via LL::WorkQueue.

This one was difficult to debug because it had all the hallmarks of a thread stomp, but adding mutexes to the data being stomped had no effect because LLMutex is not coroutine aware and is reentrant.  Locking an LLMutex from a coroutine being executed on the main thread while the lock is held by the "real" main thread doesn't wait for the lock to be released.

I don't have a good solution to this.  My preference is to strongly favor LL::WorkQueue over coroutines.

**Comment by valeriiaaproductengine** [comment]
Passed QA.

Verified on the Second Life Release 7.1.7.8883017948 (64bit) on the scope of IQA#218 on Win10/OSX systems.
